translations = {
    "DE": {
        "title": "Universal Offline Web Deployment Station",
        "status_ready": "Bereit.",
        "tab_welcome": "Willkommen",
        "tab_apk": "Android (APK)",
        "tab_esp": "Hardware Stick",
        "tab_pc": "PC Server",
        "dash_title": "Universal Offline Web Deployment Station",
        "dash_guide": "Dieses Werkzeug erlaubt es dir, Web-Assets und Server fuer deine Konsole bereitzustellen.\n\nCredits:\n- Das Hardware-Modul nutzt den nativen C++ Core und das herstellerkonforme Webserver-Framework,\num einen sicheren Port-80-HTTP-Server im privaten Heimnetzwerk bereitzustellen.\nAlle Rechte gehoeren der Entwicklergemeinschaft.",
        "apk_info": "Android-Anwendungs-Modul (Derzeit in Wartung)",
        "esp_info": "Konfiguriere hier deinen ESP8266EX-WLAN-Stick",
        "pc_info": "Lokaler Windows HTTP-Server auf Port 80",
        "btn_load_zip": "Website-ZIP laden",
        "btn_start_apk": "APK generieren",
        "btn_flash_esp": "Firmware brennen",
        "btn_mon_esp": "Live-Monitor starten",
        "btn_start_pc": "Server starten",
        "btn_stop_pc": "Server stoppen",
        "lbl_ssid": "WLAN Name (SSID):",
        "lbl_pw": "Passwort (WPA2):",
        "btn_credits": "Externe Credits anzeigen",
        "credits_text": "Universal Offline Web Deployment Station - Open-Source Quellenverweise:\n\n1. ESP8266 Core fuer Arduino SDK\n   Entwickelt von Espressif Systems und der ESP8266-Community.\n   Lizenz: GNU Lesser General Public License (LGPL v2.1).\n\n2. esptool Framework\n   Erstellt von Ivan Grokhotkov, genutzt fuer die serielle Kommunikation.\n   Lizenz: GNU General Public License (GPL v2).\n\n3. mkspiffs Werkzeug\n   Erstellt von Hristo Gochkov, genutzt fuer den Bau der Speicher-Partition.\n   Lizenz: MIT-Lizenz."
    },
    "EN": {
        "title": "Universal Offline Web Deployment Station",
        "status_ready": "Ready.",
        "tab_welcome": "Welcome",
        "tab_apk": "Android (APK)",
        "tab_esp": "Hardware Stick",
        "tab_pc": "PC Server",
        "dash_title": "Universal Offline Web Deployment Station",
        "dash_guide": "This utility allows you to deploy custom web assets and local servers for your console.\n\nCredits:\n- The hardware module utilizes the native C++ core and official webserver frameworks\nto deploy a secure Port 80 HTTP server inside your private local network.\nAll rights belong to the open-source developer community.",
        "apk_info": "Android Deployment Module (Currently under construction)",
        "esp_info": "Configure your ESP8266EX Wi-Fi dongle here",
        "pc_info": "Local Windows HTTP Server running on Port 80",
        "btn_load_zip": "Load Website ZIP",
        "btn_start_apk": "Build APK",
        "btn_flash_esp": "Flash Hardware",
        "btn_mon_esp": "Start Live Monitor",
        "btn_start_pc": "Start Server",
        "btn_stop_pc": "Stop Server",
        "lbl_ssid": "Wi-Fi Name (SSID):",
        "lbl_pw": "Password (WPA2):",
        "btn_credits": "View Open-Source Credits",
        "credits_text": "Universal Offline Web Deployment Station - Open-Source Attributions:\n\n1. ESP8266 Core for Arduino SDK\n   Developed by Espressif Systems and the ESP8266 Community.\n   License: GNU Lesser General Public License (LGPL v2.1).\n\n2. esptool Framework\n   Created by Ivan Grokhotkov, utilized for serial flashing routines.\n   License: GNU General Public License (GPL v2).\n\n3. mkspiffs toolchain\n   Created by Hristo Gochkov, used for SPIFFS binary filesystem allocation.\n   License: MIT License."
    }
}
